In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
forest = pd.read_csv('/content/train.csv')

In [3]:
forest.head(4)

   Id  Elevation  Aspect  ...  Soil_Type39  Soil_Type40  Cover_Type
0   1       2596      51  ...            0            0           5
1   2       2590      56  ...            0            0           5
2   3       2804     139  ...            0            0           2
3   4       2785     155  ...            0            0           2

[4 rows x 56 columns]

In [4]:
forest.shape

(15120, 56)

In [5]:
forest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Id                                  15120 non-null  int64
 1   Elevation                           15120 non-null  int64
 2   Aspect                              15120 non-null  int64
 3   Slope                               15120 non-null  int64
 4   Horizontal_Distance_To_Hydrology    15120 non-null  int64
 5   Vertical_Distance_To_Hydrology      15120 non-null  int64
 6   Horizontal_Distance_To_Roadways     15120 non-null  int64
 7   Hillshade_9am                       15120 non-null  int64
 8   Hillshade_Noon                      15120 non-null  int64
 9   Hillshade_3pm                       15120 non-null  int64
 10  Horizontal_Distance_To_Fire_Points  15120 non-null  int64
 11  Wilderness_Area1                    15120 non-null  int64
 12  Wilderness_Area2                    15120 non-null  int64
 13  Wilderness_Area3                    15120 non-null  int64
 14  Wilderness_Area4                    15120 non-null  int64
 15  Soil_Type1                          15120 non-null  int64
 16  Soil_Type2                          15120 non-null  int64
 17  Soil_Type3                          15120 non-null  int64
 18  Soil_Type4                          15120 non-null  int64
 19  Soil_Type5                          15120 non-null  int64
 20  Soil_Type6                          15120 non-null  int64
 21  Soil_Type7                          15120 non-null  int64
 22  Soil_Type8                          15120 non-null  int64
 23  Soil_Type9                          15120 non-null  int64
 24  Soil_Type10                         15120 non-null  int64
 25  Soil_Type11                         15120 non-null  int64
 26  Soil_Type12                         15120 non-null  int64
 27  Soil_Type13                         15120 non-null  int64
 28  Soil_Type14                         15120 non-null  int64
 29  Soil_Type15                         15120 non-null  int64
 30  Soil_Type16                         15120 non-null  int64
 31  Soil_Type17                         15120 non-null  int64
 32  Soil_Type18                         15120 non-null  int64
 33  Soil_Type19                         15120 non-null  int64
 34  Soil_Type20                         15120 non-null  int64
 35  Soil_Type21                         15120 non-null  int64
 36  Soil_Type22                         15120 non-null  int64
 37  Soil_Type23                         15120 non-null  int64
 38  Soil_Type24                         15120 non-null  int64
 39  Soil_Type25                         15120 non-null  int64
 40  Soil_Type26                         15120 non-null  int64
 41  Soil_Type27                         15120 non-null  int64
 42  Soil_Type28                         15120 non-null  int64
 43  Soil_Type29                         15120 non-null  int64
 44  Soil_Type30                         15120 non-null  int64
 45  Soil_Type31                         15120 non-null  int64
 46  Soil_Type32                         15120 non-null  int64
 47  Soil_Type33                         15120 non-null  int64
 48  Soil_Type34                         15120 non-null  int64
 49  Soil_Type35                         15120 non-null  int64
 50  Soil_Type36                         15120 non-null  int64
 51  Soil_Type37                         15120 non-null  int64
 52  Soil_Type38                         15120 non-null  int64
 53  Soil_Type39                         15120 non-null  int64
 54  Soil_Type40                         15120 non-null  int64
 55  Cover_Type                          15120 non-null  int64
dtypes: int64(56)
memory usage: 6.5 MB

In [6]:
forest.describe()

                Id     Elevation  ...   Soil_Type40    Cover_Type
count  15120.00000  15120.000000  ...  15120.000000  15120.000000
mean    7560.50000   2749.322553  ...      0.030357      4.000000
std     4364.91237    417.678187  ...      0.171574      2.000066
min        1.00000   1863.000000  ...      0.000000      1.000000
25%     3780.75000   2376.000000  ...      0.000000      2.000000
50%     7560.50000   2752.000000  ...      0.000000      4.000000
75%    11340.25000   3104.000000  ...      0.000000      6.000000
max    15120.00000   3849.000000  ...      1.000000      7.000000

[8 rows x 56 columns]

In [8]:
forest.isnull().sum()

Id                                    0
Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0
Soil_Type12                           0
Soil_Type13                           0
Soil_Type14                           0
Soil_Type15                           0
Soil_Type16                           0
Soil_Type17                           0
Soil_Type18                           0
Soil_Type19                           0
Soil_Type20                           0
Soil_Type21                           0
Soil_Type22                           0
Soil_Type23                           0
Soil_Type24                           0
Soil_Type25                           0
Soil_Type26                           0
Soil_Type27                           0
Soil_Type28                           0
Soil_Type29                           0
Soil_Type30                           0
Soil_Type31                           0
Soil_Type32                           0
Soil_Type33                           0
Soil_Type34                           0
Soil_Type35                           0
Soil_Type36                           0
Soil_Type37                           0
Soil_Type38                           0
Soil_Type39                           0
Soil_Type40                           0
Cover_Type                            0
dtype: int64

In [9]:
forest.duplicated().sum()

np.int64(0)

In [10]:
forest.columns

Index(['Id', 'Elevation', 'Aspect', 'Slope',
       'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology',
       'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon',
       'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points',
       'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3',
       'Wilderness_Area4', 'Soil_Type1', 'Soil_Type2', 'Soil_Type3',
       'Soil_Type4', 'Soil_Type5', 'Soil_Type6', 'Soil_Type7', 'Soil_Type8',
       'Soil_Type9', 'Soil_Type10', 'Soil_Type11', 'Soil_Type12',
       'Soil_Type13', 'Soil_Type14', 'Soil_Type15', 'Soil_Type16',
       'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20',
       'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24',
       'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28',
       'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32',
       'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36',
       'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_Type40',
       'Cover_Type'],
      dtype='object')

In [12]:
X = forest.drop('Cover_Type',axis=1)
y = forest['Cover_Type']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [15]:
lg = LogisticRegression()
lg.fit(X_train,y_train)
ypred = lg.predict(X_test)
accuracy_score(y_test,ypred)

0.3826058201058201

In [16]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)
ypred = dtc.predict(X_test)
accuracy_score(y_test,ypred)

0.8098544973544973

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.878968253968254

In [26]:
ypred

array([6, 6, 1, ..., 5, 4, 4])

you can add a prediction sysytem after this ...